# Generated by Django 5.1.7 on 2025-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlatformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cost_per_click', models.FloatField()),
                ('reach', models.IntegerField()),
            ],
        ),
    ]
